name: Publish Pre-release

on:
  workflow_dispatch:
    inputs:
      target-version:
        description: 'Target version being developed (e.g. 1.11.0)'
        required: true
        default: '1.11.0'
      prerelease-type:
        description: 'Pre-release type (rc or beta)'
        required: true
        default: 'rc'
        type: choice
        options:
          - 'rc'
          - 'beta'
      prerelease-number:
        description: 'Pre-release number (e.g. 0, 1, 2)'
        required: true
        default: '0'

permissions:
  contents: write

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHA_BOT_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions pre-release workflow"

      - name: Set pre-release version
        run: |
          # Create pre-release version based on target version
          TARGET_VERSION="${{ github.event.inputs.target-version }}"
          PRERELEASE_TYPE="${{ github.event.inputs.prerelease-type }}"
          PRERELEASE_NUMBER="${{ github.event.inputs.prerelease-number }}"
          PRERELEASE_VERSION="${TARGET_VERSION}-${PRERELEASE_TYPE}.${PRERELEASE_NUMBER}"
          echo "PRERELEASE_VERSION=${PRERELEASE_VERSION}" >> ${GITHUB_ENV}
          echo "RELEASE_TAG=${PRERELEASE_TYPE}" >> ${GITHUB_ENV}

          # Update versions in all packages
          npm version ${PRERELEASE_VERSION} --no-git-tag-version --allow-same-version

      - name: Publish package
        run: npm publish --verbose --access public --tag ${{ env.RELEASE_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_BOT_PAT }}

      - name: Report pre-release publish
        run: |
          echo "✅ Published pre-release packages:"
          echo "  - @richardgaunt/dist-tags@${PRERELEASE_VERSION} (tag: ${{ env.RELEASE_TAG }})"
          echo ""
          echo "These packages can be installed with:"
          echo "npm install @richardgaunt/dist-tags@${{ env.RELEASE_TAG }}"
